### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by doakey3**
I have edited much of the code in VSE_Transform_Tools.

Notable Improvements
==================
* Crop tool rewrite: Crop any transformed strip (not just MOVIE and IMAGE)
* Fixed cropping issue with PROXY strips
* Automatic Keyframing may be enabled
* Enable snapping while Grabbing and Rotating with CTRL key
* Fine tuning with Shift key works much better now for rotating, grabbing, and scaling.
* Fixed issue with transforming strips inside META
* Autocrop function added
* Keyboard shortcuts added for changing Pivot Type
* Code cleanup (separated much of the code into different modules)
* Readme updated

### CODE REVIEW

**Comment by NathanLovato** [comment]
Right when I was getting started with this :) So cool, thank you so much!
It seems there's not much activity on this repo anymore. Maybe you could start to maintain your own fork? I was going to merge it with my own add-on, [Power Sequencer](https://github.com/GDquest/Blender-power-sequencer/)

Or if you're not interested in maintaining the fork/managing the users, may I merge your rewrite with power sequencer (with all credits and license retained, as you could expect)? It came out recently as a FOSS addon, but at least I work full-time in open source education, and the idea is to use my Youtube channel etc. to help bring some devs together to work on much better VSE tools.

In any case, thank you very much for your work, it'll benefit to a lot of people :) / regardless of your decision I can't wait to cover it in a video tutorial ^^

**Comment by doakey3** [comment]
I was hoping [kgeogeo](https://github.com/kgeogeo) would merge my fork because most people come here looking for VSE_Transform_Tools. It's true that there hasn't been recent activity by [kgeogeo](https://github.com/kgeogeo). 

If you think more people would benefit if this project were merged with [Power Sequencer](https://github.com/GDquest/Blender-power-sequencer/), that's fine with me. In any case, I plan to leave [my fork](https://github.com/doakey3/VSE_Transform_Tools) on Github and I'll probably make improvements from time to time and fix issues as they come up. 

If [kgeogeo](https://github.com/kgeogeo) doesn't respond in a couple weeks, I'll make a post about the rewrite on [Blenderartists](https://blenderartists.org/forum/forumdisplay.php?48-Released-Scripts-and-Themes).

**Comment by doakey3** [comment]
Since implementing the [addon_updater](https://github.com/CGCookie/blender-addon-updater) to this project means I had to point the updater to a specific github page, I'm definitely going to be maintaining my own fork since any users who download my version will have automatic updates checking my fork.

I have included the original version of the VSE_Transform_Tools addon as version 1.0.0 of my project.

**Comment by MarioMey** [comment]
I didn't try your fork, but I think you are doing a good job by maintaining this code. Thanks!

**Comment by NathanLovato** [comment]
@doakey3 Great :) I'll point people there then.

**Pull request closed without merging**
